/home/ubuntu/ICdesign/base/uart/rtl/uart.v
/home/ubuntu/ICdesign/base/uart/rtl/uart_rx.v
/home/ubuntu/ICdesign/base/uart/rtl/uart_rx_ctrl.v
/home/ubuntu/ICdesign/base/uart/rtl/uart_tx.v
/home/ubuntu/ICdesign/base/uart/rtl/uart_tx_ctrl.v
/home/ubuntu/ICdesign/base/uart/rtl/gen_baudrate_bit.v
/home/ubuntu/ICdesign/base/uart/rtl/clocks/clk_mask.v
/home/ubuntu/ICdesign/base/uart/rtl/general_syncer/general_syncer.v
/home/ubuntu/ICdesign/base/uart/rtl/reset/reset_syncer.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/async_fifo.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/bin2gray.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/dual_port_mem.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/if_empty.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/if_full.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/read_ctrl.v
/home/ubuntu/ICdesign/base/uart/rtl/async_fifo/write_ctrl.v
/home/ubuntu/ICdesign/base/uart/rtl/status_ctrl.v
